config/routes.rb
SageoTechnologies::Application.routes.draw do
  
  resources :enquiries
  devise_for :admins
  root 'pages#home'
  get "/about",													:to => "pages#about"
  get "/services",											:to => "pages#services"
  get "/clientsAndProjects",						:to => "pages#clientsAndProjects"
  get "/contactUs",											:to => "pages#contactUs"
  get "/partners",											:to => "pages#partners"
  get "pages/create"

end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/enquiry.rb
# == Schema Information
#
# Table name: enquiries
#
#  id                 :integer          not null, primary key
#  first_name         :string(255)
#  second_name        :string(255)
#  email              :string(255)
#  subject            :string(255)
#  body               :text
#  created_at         :datetime
#  updated_at         :datetime
#  telephone_number   :string(255)
#  confirmation_email :string(255)
#

class Enquiry < ActiveRecord::Base

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :first_name,						presence: true,
																		length: {maximum: 50}
	validates :second_name,						presence: true,
																		length: {maximum: 50}
	validates :email,									presence: true,
																		format: {with: email_regex}
	validates :subject,								presence: true,
																		length: {maximum: 60}
	validates :body,									presence: true,
																		length: {maximum: 512}
	validates :telephone_number,			presence: true,
																		length: {maximum: 15}
	validates :confirmation_email,		presence: true,
																		format: {with: email_regex}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def edit
  end

  def update
  end

  def create
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :set_enquiry, only: [:home, :about, :services, :clientsAndProjects, :partners]

  def home
  	@title = "Home"
  end

  def about
  	@title = "About Us"
  end

  def services
  	@title = "Services"
  end

  def clientsAndProjects
  	@title = "Clients and Projects"
  end

  def contactUs
  	@title = "Contact Us"
  end

  def partners
  	@title = "Partners"
  end

  def create
		@enquiry = Enquiry.new(enquiry_params)
		
		if @enquiry.save
  		if EnquiryMailer.enquiry_mail(@enquiry).deliver
  			redirect_to root_path, :notice => "The enquiry was successfully sent."
  		end
  	else
  		render 'new'
  	end
  end

  private

  def set_enquiry
  	@enquiry = Enquiry.new
  end

  def enquiry_params
  	params.require(:enquiry).permit(:first_name, :second_name, :telephone_number, :email,
  	:confirmation_email, :subject, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return the title on a per page basis
	def title
		base_title = "Sageo Technologies"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end

end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/enquiries/create.html.erb
<h1>Enquiries#create</h1>
<p>Find me in app/views/enquiries/create.html.erb</p>

app/views/enquiries/destroy.html.erb
<h1>Enquiries#destroy</h1>
<p>Find me in app/views/enquiries/destroy.html.erb</p>

app/views/enquiries/edit.html.erb
<h1>Enquiries#edit</h1>
<p>Find me in app/views/enquiries/edit.html.erb</p>

app/views/enquiries/index.html.erb
<h1>Enquiries#index</h1>
<p>Find me in app/views/enquiries/index.html.erb</p>

app/views/enquiries/new.html.erb
<div class="row">
	<div class="small-7 columns round">
		
		<%= render "layouts/contactusform" %>

	</div>
	
	
	<div class="small-5 columns round" style="margin-top:20px;">
	
		<%= render "layouts/searchfield" %>
		
		<form>
			<fieldset class="round" style="background-color: #FFFFFF; margin-top: 20px;">
				<legend>Additional contact information</legend>
				<label>+254 020 2345423</label> <br />
				<label>+254 0722-706701</label> <br />
				<label>info@sageotech.com</label> <br /> 
				<label>Twitter: @sageotechnologies</label> <br />
				<label>Facebook: Sageo Technologies</label> <br />
			</fieldset>
		</form>
		
		<%= render "layouts/socialbar"%>
		
	</div>
	
	
</div>

app/views/enquiries/show.html.erb
<div class="row">
	<div class="small-12 columns">
		<p class="enquiries"><%= link_to "Back", enquiries_path %></p>
	</div>
</div>

<div class="center">
	<%= @enquiry.email %>
</div>

app/views/enquiries/update.html.erb
<h1>Enquiries#update</h1>
<p>Find me in app/views/enquiries/update.html.erb</p>

app/views/layouts/_contentforhomepage.html.erb
<p>
					Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
					Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
					Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
					Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
					Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
					Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
					Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
					Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
</p>

<p>
			Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
					Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
					Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
					Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
					Today we will teach you how to perform port scanning with the TCP/IP Swiss Army Knife tool, netcat.
</p>

app/views/layouts/_footer.html.erb
<div class="partners" style="margin-top: 20px;">
	<div class="row">
		<div class="small-3 columns">
			<%= link_to (image_tag "awslogo.png"), "#" %>
		</div>
		<div class="small-3 columns">
			<%= link_to (image_tag "citrixsolutionlogo.png"), "#" %>
		</div>
		<div class="small-3 columns">
			<%= link_to (image_tag "microsoftpartnerlogo1.jpg"), "#" %>
		</div>
		<div class="small-3 columns">
			<%= link_to (image_tag "symanteclogo.png"), "#"%>
		</div>
	</div>
</div>




<div class="footer" id="footerdesign">
	<div class="row" id="navcontainer">
		<div class="small=9 columns">
			<div class="row" id="navcontainer">
				<div class="small-12 columns">
					<ul class="">
						<li><%= link_to "Home", root_path %></li>
						<li><%= link_to "About Us", about_path %></li>
						<li><%= link_to "Services", services_path %> </li>
						<li><%= link_to "Clients And Projects", clientsAndProjects_path %> </li>
						<li><%= link_to "Partners", partners_path %> </li>
						<li><%= link_to "Contact Us", new_enquiry_path %> </li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="small-12 columns">
					<!--Partners-->
					
				</div>
			</div>
			<div class="row">
				<div class="small-12 columns">
					<p class="copyright" style="text-align: center">&copy;2014 Sageo Technologies Limited. All rights rerserved.
						<%= link_to (image_tag "sageominilogo.png", :class => "round"), root_path %>
					</p>
				</div>
			</div>
		</div>
		
		<div class="small-3 columns">
			
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<!-- Mobile nav header -->
  <div class="row show-for-small offcanvas-toggle">
    <div class="large-12 columns">
      <a class="sidebar-button" id="sidebarButton" href="#sidebar">
        <h4>Sageo Technologies</h4>
      </a>
    </div>
  </div>
  <!-- /Mobile nav header -->

  <!-- Sageo topbar -->
  <nav class="top-bar hide-for-small" data-top-bar>
    <ul class="title-area" >
      <!-- Title Area -->
      <li class="name">
        <h1><a class="#" href="#">Sageo <strong>Technologies</strong></a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>

    <section class="top-bar-section" >
      <!-- Right Nav Section -->
      <ul class="right">
        <li><%= link_to "Services", services_path %></li>
        <li><%= link_to "Clients and Projects", clientsAndProjects_path %></li>
        <li><%= link_to "Partners", partners_path %></li>
        <li><a href="#" data-reveal-id="contactUs">Contact Us</a></li>
        
        <% if admin_signed_in? %>
        
        	<li class=""><a href="#" data-dropdown="hover1" data-options="is_hover:true"><%= current_admin.email %> </a>
        		<ul id="hover1" class="f-dropdown" data-dropdown-content>
        			<li><%= link_to "View enquiries", enquiries_path %></li>
        			<li><%= link_to "Edit profile", edit_admin_registration_path %></li>
        			<li><%= link_to "Change password", edit_admin_password_path %></li>
        			<li><%= link_to "Create new admin", new_admin_registration_path %></li>
        			<li><%= link_to "Log out", destroy_admin_session_path, :method => :delete %></li>
        		</ul>
        	</li>
        
        <% else %>
        
        	<li><%= link_to "Login", new_admin_session_path %></li>
        
        <% end %>
        
        <div id="contactUs" class="reveal-modal round medium" data-revela>
        	<h4>Write To Us</h4>
        	<%= render "layouts/contactusform"%>
        	<a class="close-reveal-modal">&#215;</a>
        </div>
      </ul>
    </section>
  </nav>
  <!-- Sageo topbar -->

  <!-- Desktop header/nav -->
  <div class="header hide-for-small">
    <div class="row">
      <div class="large-7 columns logo">
        <%= link_to(image_tag "sageologo.png", :class => "round") %>

      </div>
      <div class="large-5 columns">
        <ul class="navigation">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About Us", about_path %></li>
          <li><a href="#" class="button tiny round" data-reveal-id="myModal" >Contact</a></li>

          <div id="myModal" class="reveal-modal round small" data-reveal >
          	<form>
          		<fieldset class="radius">
          			<legend>Our Contacts</legend>
          			<label>+254 020 2345423</label> <br />
								<label>+254 0722-706701</label> <br />
								<label>info@sageotech.com</label> <br /> 
								<label>Twitter: @sageotechnologies</label> <br />
								<label>Facebook: Sageo Technologies</label> <br />
          		</fieldset>
          	</form>
          	<a class="close-reveal-modal">&#215;</a>
          </div>
        </ul>
      </div>
    </div>
  </div>
  <!-- /Header/nav -->

app/views/layouts/_infoslider.html.erb
<!--A slider for additional information goes here-->
			<ul class="example-orbit-content" data-orbit>
  			<li data-orbit-slide="headline-1">
    			<div>
      			<h3 style="text-align:center;">Heading 1</h3>
      			<p>
      				Information and News go here.<br/>
      				Information and News go here.<br/>
      				Information and News go here.
      			</p>
    			</div>
  			</li>
  			<li data-orbit-slide="headline-2">
    			<div>
      			<h3 style="text-align:center;">Heading 2</h3>
      			<p>
      				Information and News go here.<br/>
      				Information and News go here.<br/>
      				Information and News go here.
      			</p>
    			</div>
  			</li>
  			<li data-orbit-slide="headline-3">
    			<div>
      			<h3 style="text-align:center;">Heading 3</h3>
      			<p>
      				Information and News go here.<br/>
      				Information and News go here.<br/>
      				Information and News go here.
      			</p>
    			</div>
  			</li>
			</ul>

app/views/layouts/_offcanvasnavigation.html.erb
<div class="off-canvas-wrap">
	<div class="inner-wrap">
		<nav class="tab-bar">
			<section class="left-small">
				<a class="left-off-canvas-toggle menu-icon"><span></span></a>
			</section>
			<section class="middle tab-bar-section">
				<h1 class="title">Sageo Technologies</h1>
			</section>
		</nav>

		<!--Off Canvas Menu-->
		<aside class="left-off-canvas-menu">
			<!--Whatever you want goes here-->
			<ul class="off-canvas-list">
				<li><a href="#">Who We Are</a></li>
				<li><a href="#">Partners</a></li>
				<li><a href="#">Services We Offer</a></li>
				<li><a href="#">Projects</a></li>
				<li><a href="#">Ongoing Projects</a></li>
				<li><a href="#">Company Fun Outs</a></li>
			</ul>
		</aside>
	
		<!--Main Content Goes Here-->
		<section class="main-section offCanvasContent">
			<%= render "layouts/contentforhomepage"%>
		</section>
	
	
		<!--Close the off-canvas menu-->
		<a class="exit-off-canvas"></a>
	</div>
</div>			

app/views/layouts/_panel2.html.erb
<h3 style="text-align:center;">MISSION STATEMENT</h3>
<p class="panels round">
Our mission is to provide comprehensive, efficient and reliable IT solutions to the
business community, public institutions and individuals using the most up to date
technology.
</p>


<h3 style="text-align:center;">OUR VISION</h3>
<p class="panels round">
	To be a leading strategic IT solutions provider.
</p>


<h3 style="text-align:center;">OBJECTIVES</h3>
<p class="panels round">
	STL’s business objective is to provide value to the customers through computer based
solutions and applications profitable to both the customer and STL.
</p>

app/views/layouts/_panel3.html.erb
<h3 style="text-align: center;">PARTNERSHIPS</h3>

<p class="panels round">
	Sageo Technologies Limited is in partnership with several companies along the line of offering quality services to its customers. These partners inlcude:
</p>

<ul id="whatweoffer">
	<li>Microsoft</li>
	<li>Symantec</li>
	<li>Amazon</li>
	<li>Citrix</li>
	<li>HP</li>
</ul>


<div class="row">
	<div class="small-6 columns">
		<a class="th [radius]" href="#">
			<%= image_tag "microsoftpartnerlogo1.jpg" %>
		</a>
	</div>
	<div class="small-6 columns">
		<a class="th [radius]" href="#">
			<%= image_tag "symanteclogo.png" %>
		</a>
	</div>
</div>

<div class="row" style="margin-top: 20px;">
	<div class="small-6 columns">
		<a class="th [radius]" href="#">
			<%= image_tag "citrixsolutionlogo.png" %>
		</a>
	</div>
	<div class="small-6 columns">
		<a class="th [radius]" href="#">
			<%= image_tag "awslogo.png" %>
		</a>
	</div>
</div>

app/views/layouts/_panel4.html.erb
In 60 BC Caesar's career took him back to Spain. Aged 41, he was awarded the post of praetor. It may well have been that the senate decided to send the young upstart to a troubled region, in order to have him fail.
Trouble had been brewing with the local tribes in Spain for a long time. But Caesar undaunted by the problems, excelled in his new role.
Caesar discovered a talent for military command which he himself hadn't known he possessed. The experience he gained in Spain would be of great value in his further career. But more so the ability of capturing some spoils of war for himself, to put his personal finances back to right and repay his debt was what rescued his career.
If there was one lesson, Caesar learnt in Spain then it was that war could be politically and financially very profitable. 

app/views/layouts/_panel5.html.erb
In 59 BC Caesar returned to Rome, having proved himself a capable ruler. He now formed a valuable pact with two of the most prominent Romans of the day, - the so-called 'first triumvirate'.

The triumvirate helped Caesar achieve his greatest ambition to that day. He was elected consul, the highest office of Rome.
The political influence he had built up in his previous years of bribery, together with the enormous power and influence of Crassus and Pompey managed to virtually oust the second consul, L. Calpurnius Bibulus, who stayed at home for most of the time, knowing he had little say at all. The historian Suetonius tells of people joking of it being not the joint consulship of 'Bibulus and Caesar', but of 'Julius and Caesar'.
The formation of the ruling triumvirate with Crassus and Pompey was a mark also of Caesar's determination to push through genuine and innovative measures in the face of a hostile senate which was suspicious of his motives and to ensure that there was some continuity of progressive legislation after his term as consul was over.

Caesar's laws are indeed seen as more than mere populist measures. For example, tax demands on farmers were cancelled. Public land was allocated to fathers of three or more children. These were laws hardly likely to make Caesar less popular than he was, and yet they reveal that he also possessed insight into the problems weighing on Rome at the time.

Caesar also remarried, once again to a bride from a very influential Roman household. And his daughter Julia was married to Pompey, further cementing his political partnership with the great general. 

app/views/layouts/_panel6.html.erb
<p class="panels round">
	STL consults in all matters pertaining to IT and the basis of adaptation and at the same
time affiliates itself with globally recognized applications redistributed and utilized
under the STL umbrella. The services are categorized as below:
</p>

<h5 style="text-align: center;">IT Infrastructure Solutions</h5>
<p class="panels round">
STL has extensive experience in the design topology, planning and implementation of a
wide range of systems:
</p>

<ul id="whatweoffer">
		<li>Server deployments</li>
		<li>Mail Server Solutions</li>
		<li>Antivirus/Antispam Solutions via Symantec and GFI</li>
		<li>Citrix Thin Client Solutions</li>
		<li>Localized virtual Server computing Solutions</li>
		<li>Virtual Server Computing Solutions via Amazon</li>
		<li>Offsite Backup Solutions via Amazon</li>
		<li>Hardware Sales (Laptops, Desktops, Routers, Servers, UPS)</li>
		<li>Software Sales (Windows 8, Microsoft Office Suite, Windows Server OS)</li>
	</ul>

<h5 style="text-align: center;">I.T Outsourcing</h5>
<p class="panels round">
	STL keeps your businesses IT operations running day-to-day. Our customer focus and
customized approach allow us to tailor our approach to supplement your existing IT
resources or assume the role of your IT department.
</p>

<ul id="whatweoffer">
		<li>Managed IT Services</li>
		STL’s Managed IT Services tailor to your organization helping you maximize
your IT return on investment while minimizing the impact on your business
from the threats of the Internet.
	<li>Help Desk Services</li>
	For quick troubleshooting of your issues, our Help Desk is equipped with the
latest in remote technologies allowing your issues to be addressed in real-time
while you watch.
	<li>Backup Solutions</li>
	Data loss is one of the greatest impacts to businesses today. STL works with
clients to establish Backup routines to protect against data failures.
	<li>Security Solutions</li>
	Not all threats to security come from outside your organization. STL reviews
networks to identify vulnerabilities and manages policies to protect you.
	<li>IT Monitoring and Maintenance</li>
	Viruses, Hackers and other network risks feed on outdated computers and
servers. STL monitors our client's networks to protect against these threats, while
performing IT preventative maintenance.
	<li>Performance Management</li>
	IT system performance drives business productivity. STL’s organizational focus
ensures that resources are allocated efficiently to maximize the return on your
investment.
</ul>

<p class="panels round">
	We provide IT support services to help keep your business operations running
day to day. Through our Help Desk, we offer support in real time to help you
quickly resolve any issues. We use advanced remote technologies that allow us
to address issues immediately for computers, servers, switches, as well as
software issues.
In our IT outsourcing and IT support services, we always use a customer focus
approach. This focus allows us to tailor our services to the specific need of each
client. We can help by analyzing your needs and supplementing your existing IT
resources or assume the role of your IT department.
</p>

app/views/layouts/_panel7.html.erb
<p class="panels round">
	STL’s core values are:
</p>

<ul id="whatweoffer">
	<li>To create public awareness on the availability, use and benefits of a variety of IT
solutions.</li>
	<li>Professional advice on key implementations and adaptations based on business
structures.</li>
	<li>To operate with honesty and integrity at all times.</li>
	<li>To be customer focused and provide value for money.</li>
	<li>To perform to the highest level of competence at all times.</li>
	<li>To be a socially responsible company and do business in a prudent, ethical and
environmentally friendly manner.</li>
</ul>

app/views/layouts/_searchfield.html.erb
<form>
	<div class="row">
		<div class="small-12 columns">
			<div class="row collapse">
				<div class="small-9 columns">
					<input type="text" placeholder="Search..." />
				</div>
				<div class="small-3 columns">
					<a href="#" class="button postfix">Search</a>
				</div>
			</div>
		</div>
	</div>
</form>

app/views/layouts/_socialbar.html.erb
<div class="row">
		<div class="small-12 columns socialbar round">
			<h3 style="text-align: center;">Social Media</h3>
			<hr />
			Facebook
			<hr />
			Twitter <a href="http://twitter.com/share" class="twitter-share-button" data-count="vertical" data-via="sageotechnologies-herokuapp.com">Tweet</a>
			<hr />
			Google + <g:plusone></g:plusone>
			<hr />
			Reddit <a href="http://www.reddit.com/submit" onclick="window.location = 'http://www.reddit.com/submit?url=' + encodeURIComponent(window.location); return false"> <img src="http://www.reddit.com/static/spreddit7.gif" alt="submit to reddit" border="0" /> </a>
			<hr />
			<img src="http://l.yimg.com/hr/img/delicious.small.gif" height="10" width="10" alt="" />
<a href="http://www.delicious.com/save" onclick="window.open('http://www.delicious.com/save?v=5&noui&jump=close&url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title), 'delicious','toolbar=no,width=550,height=550'); return false;"> Bookmark this on Delicious</a>
	</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= stylesheet_link_tag "stylesheet/custom.css" %>
    <%= csrf_meta_tags %>

app/views/pages/about.html.erb
<div class="row">
	<div class="small-12 columns">
		<%= image_tag "sky3.jpg", :style => "margin-top: 20px;", :class => "round" %>
		<div class="small-9 columns abouttabs">
			<dl class="tabs vertical" data-tab>
				<dd class="active"><a href="#panel1a">Our Company</a></dd>
				<dd><a href="#panel2a">Vision an Mission</a></dd>
				<dd><a href="#panel6a">Products and Services</a></dd>
				<dd><a href="#panel7a">Core Values</a></dd>
				<dd><a href="#panel3a">Our Partners</a></dd>
				<dd><a href="#panel4a">Message from CEO</a></dd>
				<dd><a href="#panel5a">Management Team</a></dd>
			</dl> <div class="tabs-content vertical">
			<div class="content active" id="panel1a">
				<%=  render "layouts/panel1" %>
			</div>
			<div class="content" id="panel2a">
				<%=  render "layouts/panel2" %>
			</div>
			<div class="content" id="panel6a">
				<%=  render "layouts/panel6" %>
			</div>
			<div class="content" id="panel7a">
				<%=  render "layouts/panel7" %>
			</div>
			<div class="content" id="panel3a">
				<%=  render "layouts/panel3" %>
			</div>
			<div class="content" id="panel4a">
				<p class="panels round">
					<%=  render "layouts/panel4" %>
				</p>
			</div>
			<div class="content" id="panel5a">
				<p class="panels round">
					<%=  render "layouts/panel5" %>
				</p class="panels">
			</div>
		</div>
	</div>
	<div class="small-3 columns sidebar">
		<%= render "layouts/sidebar"%>
	</div>

</div>

app/views/pages/contactUs.html.erb
<div class="row">
	<div class="small-7 columns round">
		
		<%= render "layouts/contactusform" %>

	</div>
	
	
	<div class="small-5 columns round" style="margin-top:20px;">
	
		<%= render "layouts/searchfield" %>
		
		<form>
			<fieldset class="round" style="background-color: #FFFFFF; margin-top: 20px;">
				<legend>Additional contact information</legend>
				<label>+254-1234567890</label> <br />
				<label>sageotechnologies@sageo.com</label> <br /> 
				<label>@sageotechnologies</label> <br />
				<label>Sageo Technologies</label> <br />
			</fieldset>
		</form>
		
		<%= render "layouts/socialbar"%>
		
	</div>
	
	
</div>

app/views/pages/home.html.erb
<!-- Place somewhere in the <body> of your page -->
<div class="row">
	<div class="small-12 columns">
		<div class="flexslider">
  		<ul class="slides">
    		<li>
      		<img src="/assets/slider1.png" />
    		</li>
    		<li>
      		<img src="/assets/slider2.png" />
    		</li>
    		<li>
      		<img src="/assets/slider3.png" />
    		</li>
    		<li>
      		<img src="/assets/slider4.png" />
    		</li>
    		<li>
      		<img src="/assets/slider5.png" />
    		</li>
  		</ul>
		</div>
	</div>
</div>


<div class="row">
	<div class="small-9 columns">
		<div class="row">
			<div class="small-12 columns">
			<!--The navigation goes here-->
			<!--An Off-Canvas navigation-->
			
			<%= render "layouts/offcanvasnavigation" %>
			
			</div>
		</div>
		
		<div class="row">
			<div class="small-11 columns infoslider round">
				<!--The info slider goes here-->
				<%= render "layouts/infoslider"%>
			</div>
		</div>
		
	</div>
			
		
	<div class="small-3 columns">
		<!--The side bar goes here-->
		<%= render "layouts/sidebar" %>
	</div>
</div>

app/views/shared/_enquiry_error_messages.html.erb
<% if @enquiry.errors.any? %>
	<div id="error_explanation" class="round">
		<h2>
			<%= pluralize(@enquiry.errors.count, "error") %>
			prohibited this enquiry from being sent:
		</h2>

		<p>
			There were problems with the following fields:
		</p>
		<ul>
			<%= @enquiry.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>

	</div>
<% end %>